version: '3'
services:
  url:
     image: reader:latest
     container_name: reader
     restart: always
#     volumes:
#       - ./app:/app
#     networks:
#       - traefik_proxy
#     labels:
#       - "traefik.enable=true"
#       - "traefik.docker.network=traefik_proxy"
#       - "traefik.frontend.rule=Host:reader.romanpeters.nl"
#       - "traefik.port=5000"
#
#networks:
#  traefik_proxy:
#    external: true